os: linux

notifications:
  recipients:
    - guid_jan@yahoo.co.jp
  on_success: always
  on_failure: always

branches:
  only:
    - lein-run
#	except:
#         - develop

matrix:
  include:
    - language: clojure
      jdk:
        - openjdk11
      before_script:
        - sh /tmp/aaa.sh
      script:
        - lein run
#    - language: node_js
#      script:
#        - npm test




