os: linux

notifications:
  recipients:
    - guid_jan@yahoo.co.jp
  on_success: always
  on_failure: always

branches:
  only:
    - lein-ring
#	except:
#         - develop

matrix:
  include:
    - language: clojure
      jdk:
        - openjdk11
      before_script:
		 - lein ring server-headless 2>&1 >/tmp/server.log &
      script:
		 - /bin/sh ./test.sh
#      after_script:
#        - echo "@@@@@"
#    - language: node_js
#      script:
#        - npm test




